import { getInput, setOutput, setFailed, info } from '@actions/core';
import { execFileSync } from 'child_process';
import OpenAI from 'openai';

/**
 * Format raw git log output into a bullet list for the prompt.
 * @param {string} rawCommits - Output from `git log --pretty=format:'%h %s'`
 * @returns {string} Bullet list of commits
 */
function formatCommits(rawCommits: string): string {
  return rawCommits
    .split('\n')
    .filter((line) => line.trim().length > 0)
    .map((line) => `- ${line}`)
    .join('\n');
}

/**
 * Build the prompt sent to OpenAI for release notes generation.
 * @param {string} tag - Release tag
 * @param {string} previousTag - Previous tag (or empty)
 * @param {string} commitsList - Formatted commits list
 * @returns {string} The prompt text
 */
function buildPrompt(
  tag: string,
  previousTag: string,
  commitsList: string
): string {
  return `
Generate excellent GitHub release notes in Markdown.

Release tag: ${tag}
Previous tag: ${previousTag || 'None'}

Commits:
${commitsList || '_No commits found_'}

Requirements:
- Use clear Markdown (## Highlights, ## Fixes, ## Changes).
- Summarize commits into readable text.
- Group related topics.
- Avoid repeating raw commit messages verbatim.
`;
}

type NotesCompletion = {
  choices?: Array<{
    message?: { content?: string | null };
  }>;
};

/** Extract release notes, falling back when response content is missing. */
function extractNotes(completion: NotesCompletion, tag: string): string {
  return (
    completion.choices?.[0]?.message?.content?.trim() ||
    `# Release ${tag}\n\n_Auto-generated notes unavailable._`
  );
}

/** Append one canonical footer, replacing any existing trailing Castoff footers. */
function appendAttribution(notes: string, model: string): string {
  const body = notes
    .trimEnd()
    .replace(
      /(?:(?:^|\r?\n)\s*---\r?\nGenerated by \[Castoff\]\(https:\/\/github\.com\/everydaydevopsio\/castoff\) using OpenAI model `[^`\r\n]+`\.\s*)+$/,
      ''
    )
    .trimEnd();
  return `${body}\n\n---\nGenerated by [Castoff](https://github.com/everydaydevopsio/castoff) using OpenAI model \`${model}\`.`;
}

/**
 * Parse and validate max_commits input from workflow config.
 * @param {string} value - Raw max_commits input
 * @returns {number} Parsed positive integer in allowed bounds
 */
function parseMaxCommits(value: string): number {
  const parsed = Number.parseInt(value || '200', 10);
  if (!Number.isInteger(parsed) || parsed < 1 || parsed > 1000) {
    throw new Error(
      "Input 'max_commits' must be an integer between 1 and 1000."
    );
  }
  return parsed;
}

async function run(): Promise<void> {
  try {
    const apiKey = getInput('openai_api_key', { required: true });
    const model =
      getInput('model') || process.env.OPENAI_MODEL?.trim() || 'gpt-6-astra';
    const tag = getInput('tag', { required: true });
    const maxCommits = parseMaxCommits(getInput('max_commits'));

    info(`Generating release notes with model: ${model}`);
    const client = new OpenAI({ apiKey });

    let previousTag = '';
    try {
      previousTag = execFileSync(
        'git',
        ['describe', '--tags', '--abbrev=0', 'HEAD^'],
        { encoding: 'utf8' }
      ).trim();
    } catch {
      info('No previous tag found (first release).');
    }

    const logRange = previousTag ? `${previousTag}..HEAD` : 'HEAD';
    const rawCommits = execFileSync(
      'git',
      ['log', '--pretty=format:%h %s', logRange, '-n', String(maxCommits)],
      { encoding: 'utf8' }
    ).trim();

    const commitsList = formatCommits(rawCommits);
    const prompt = buildPrompt(tag, previousTag, commitsList);

    const completion = await client.chat.completions.create({
      model,
      messages: [
        {
          role: 'system',
          content:
            'You are an expert technical writer who crafts concise, high-quality release notes.'
        },
        { role: 'user', content: prompt }
      ]
    });

    const notes = appendAttribution(extractNotes(completion, tag), model);

    setOutput('release_notes', notes);
    setOutput('model', model);
    info('AI release notes generated successfully.');
  } catch (error) {
    setFailed(error instanceof Error ? error.message : String(error));
  }
}

export {
  formatCommits,
  buildPrompt,
  extractNotes,
  appendAttribution,
  parseMaxCommits,
  run
};
