import { getInput, setOutput, setFailed, info } from '@actions/core';
import { execFileSync } from 'child_process';
import OpenAI from 'openai';

/** Match the `chore: release <version>` commit the release workflow creates. */
const RELEASE_COMMIT_PATTERN =
  /^\S+\s+chore: release v?\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)*$/;

/**
 * Format raw git log output into a bullet list for the prompt.
 * Release chores are dropped: the workflow commits one before generating notes,
 * and it describes the release rather than a change within it.
 * @param {string} rawCommits - Output from `git log --pretty=format:'%h %s'`
 * @returns {string} Bullet list of commits
 */
function formatCommits(rawCommits: string): string {
  return rawCommits
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !RELEASE_COMMIT_PATTERN.test(line))
    .map((line) => `- ${line}`)
    .join('\n');
}

/**
 * Build the prompt sent to OpenAI for release notes generation.
 * @param {string} tag - Release tag
 * @param {string} previousTag - Previous tag (or empty)
 * @param {string} commitsList - Formatted commits list
 * @returns {string} The prompt text
 */
function buildPrompt(
  tag: string,
  previousTag: string,
  commitsList: string
): string {
  return `
Generate excellent GitHub release notes in Markdown.

Release tag: ${tag}
Previous tag: ${previousTag || 'None'}

Commits:
${commitsList || '_No commits found_'}

Requirements:
- Use clear Markdown (## Highlights, ## Fixes, ## Changes).
- Summarize commits into readable text.
- Group related topics.
- Avoid repeating raw commit messages verbatim.
`;
}

type NotesCompletion = {
  choices?: Array<{
    message?: { content?: string | null };
  }>;
};

/** Extract release notes, falling back when response content is missing. */
function extractNotes(completion: NotesCompletion, tag: string): string {
  return (
    completion.choices?.[0]?.message?.content?.trim() ||
    `# Release ${tag}\n\n_Auto-generated notes unavailable._`
  );
}

/** Match one or more canonical Castoff footers at the end of a note body. */
const ATTRIBUTION_FOOTER_PATTERN =
  /(?:(?:^|\r?\n)\s*---\r?\nGenerated by \[Castoff\]\(https:\/\/github\.com\/everydaydevopsio\/castoff\) using OpenAI model `[^`\r\n]+`\.\s*)+$/;

/** Remove any trailing Castoff attribution footers from a note body. */
function stripAttribution(notes: string): string {
  return notes.trimEnd().replace(ATTRIBUTION_FOOTER_PATTERN, '').trimEnd();
}

/** Append one canonical footer, replacing any existing trailing Castoff footers. */
function appendAttribution(notes: string, model: string): string {
  return `${stripAttribution(notes)}\n\n---\nGenerated by [Castoff](https://github.com/everydaydevopsio/castoff) using OpenAI model \`${model}\`.`;
}

/**
 * Shift Markdown ATX headings one level deeper so note sections nest under a
 * changelog version heading. Headings inside fenced code blocks are content.
 * @param {string} notes - Markdown note body
 * @returns {string} Notes with headings demoted, level six unchanged
 */
function demoteHeadings(notes: string): string {
  let fence = '';
  return notes
    .split('\n')
    .map((line) => {
      const marker = /^ {0,3}(`{3,}|~{3,})/.exec(line)?.[1];
      if (marker) {
        // CommonMark: a closing fence repeats the opening character and is at
        // least as long, so a shorter inner fence stays part of the content.
        if (!fence) fence = marker;
        else if (marker[0] === fence[0] && marker.length >= fence.length)
          fence = '';
        return line;
      }
      return fence ? line : line.replace(/^(#{1,5})(\s)/, '#$1$2');
    })
    .join('\n');
}

/** Format a date as an ISO calendar date in UTC, as Keep a Changelog expects. */
function formatReleaseDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/**
 * Build a Keep a Changelog entry from generated notes.
 * @param {string} notes - Release notes, with or without attribution
 * @param {string} tag - Release tag (e.g. v1.2.3)
 * @param {string} date - ISO calendar date for the release
 * @returns {string} Entry headed by the dated version, sections demoted
 */
function buildChangelogEntry(notes: string, tag: string, date: string): string {
  const version = tag.replace(/^v/, '');
  const body = demoteHeadings(stripAttribution(notes)).trim();
  return `## [${version}] - ${date}\n\n${body || '_No release notes were generated._'}`;
}

/**
 * Floating major tags (v1, v2, ... v99) that release workflows move onto each
 * release in a major series. They sit on the same commit as the exact version
 * tag, so `git describe` can report them in its place.
 */
const FLOATING_MAJOR_TAGS = ['v[0-9]', 'v[0-9][0-9]'];

/**
 * Read the nearest tag before HEAD.
 * @param {boolean} exact - Skip floating major tags in favour of version tags
 * @returns {string} Tag name
 */
function describePreviousTag(exact: boolean): string {
  const excludes = exact
    ? FLOATING_MAJOR_TAGS.flatMap((pattern) => ['--exclude', pattern])
    : [];
  return execFileSync(
    'git',
    ['describe', '--tags', '--abbrev=0', ...excludes, 'HEAD^'],
    { encoding: 'utf8' }
  ).trim();
}

/**
 * Parse and validate max_commits input from workflow config.
 * @param {string} value - Raw max_commits input
 * @returns {number} Parsed positive integer in allowed bounds
 */
function parseMaxCommits(value: string): number {
  const parsed = Number.parseInt(value || '200', 10);
  if (!Number.isInteger(parsed) || parsed < 1 || parsed > 1000) {
    throw new Error(
      "Input 'max_commits' must be an integer between 1 and 1000."
    );
  }
  return parsed;
}

async function run(): Promise<void> {
  try {
    const apiKey = getInput('openai_api_key', { required: true });
    const model =
      getInput('model') || process.env.OPENAI_MODEL?.trim() || 'gpt-6-astra';
    const tag = getInput('tag', { required: true });
    const maxCommits = parseMaxCommits(getInput('max_commits'));

    info(`Generating release notes with model: ${model}`);
    const client = new OpenAI({ apiKey });

    let previousTag = '';
    try {
      previousTag = describePreviousTag(true);
    } catch {
      // Fall back for repositories that tag releases some other way, and for
      // git versions without --exclude. Both ranges cover the same commits
      // when a floating major tag is all that is left to find.
      try {
        previousTag = describePreviousTag(false);
      } catch {
        info('No previous tag found (first release).');
      }
    }

    const logRange = previousTag ? `${previousTag}..HEAD` : 'HEAD';
    const rawCommits = execFileSync(
      'git',
      ['log', '--pretty=format:%h %s', logRange, '-n', String(maxCommits)],
      { encoding: 'utf8' }
    ).trim();

    const commitsList = formatCommits(rawCommits);
    const prompt = buildPrompt(tag, previousTag, commitsList);

    const completion = await client.chat.completions.create({
      model,
      messages: [
        {
          role: 'system',
          content:
            'You are an expert technical writer who crafts concise, high-quality release notes.'
        },
        { role: 'user', content: prompt }
      ]
    });

    const notes = appendAttribution(extractNotes(completion, tag), model);

    setOutput('release_notes', notes);
    setOutput(
      'changelog_entry',
      buildChangelogEntry(notes, tag, formatReleaseDate(new Date()))
    );
    setOutput('model', model);
    info('AI release notes generated successfully.');
  } catch (error) {
    setFailed(error instanceof Error ? error.message : String(error));
  }
}

export {
  formatCommits,
  buildPrompt,
  extractNotes,
  appendAttribution,
  demoteHeadings,
  formatReleaseDate,
  buildChangelogEntry,
  parseMaxCommits,
  run
};
