import { beforeEach, describe, expect, it, jest } from '@jest/globals';
import type * as core from '@actions/core';
import type { ExecFileSyncOptionsWithStringEncoding } from 'node:child_process';
import type { ChatCompletionCreateParamsNonStreaming } from 'openai/resources/chat/completions';

type Completion = Parameters<typeof import('./index.js').extractNotes>[0];
type ExecGit = (
  command: string,
  args: readonly string[],
  options: ExecFileSyncOptionsWithStringEncoding
) => string;
type CreateCompletion = (
  request: ChatCompletionCreateParamsNonStreaming
) => Promise<Completion>;

describe('run', () => {
  let coreMock: jest.Mocked<
    Pick<typeof core, 'getInput' | 'info' | 'setOutput' | 'setFailed'>
  >;
  let execFileSyncMock: jest.Mock<ExecGit>;
  let createCompletionMock: jest.Mock<CreateCompletion>;
  let run: typeof import('./index.js').run;

  beforeEach(async () => {
    jest.resetModules();

    coreMock = {
      getInput: jest.fn<typeof core.getInput>(),
      info: jest.fn<typeof core.info>(),
      setOutput: jest.fn<typeof core.setOutput>(),
      setFailed: jest.fn<typeof core.setFailed>()
    };

    execFileSyncMock = jest.fn<ExecGit>();
    createCompletionMock = jest.fn<CreateCompletion>();

    jest.unstable_mockModule('@actions/core', () => ({
      getInput: coreMock.getInput,
      info: coreMock.info,
      setOutput: coreMock.setOutput,
      setFailed: coreMock.setFailed
    }));

    jest.unstable_mockModule('child_process', () => ({
      execFileSync: execFileSyncMock
    }));

    jest.unstable_mockModule('openai', () => ({
      default: jest.fn().mockImplementation(() => ({
        chat: {
          completions: {
            create: createCompletionMock
          }
        }
      }))
    }));

    ({ run } = await import('./index.js'));
  });

  it.each([
    ['', undefined, 'gpt-6-astra'],
    ['', '', 'gpt-6-astra'],
    ['', '   ', 'gpt-6-astra'],
    ['', '  gpt-5.6-sol  ', 'gpt-5.6-sol'],
    ['', 'gpt-5.6-sol', 'gpt-5.6-sol'],
    ['gpt-6-astra', 'gpt-5.6-sol', 'gpt-6-astra']
  ])(
    'selects model from input %s and environment %s',
    async (input, envModel, expected) => {
      const previous = process.env.OPENAI_MODEL;
      if (envModel === undefined) delete process.env.OPENAI_MODEL;
      else process.env.OPENAI_MODEL = envModel;
      try {
        const inputs: Record<string, string> = {
          openai_api_key: 'test-key',
          model: input,
          tag: 'v1.0.0',
          max_commits: '10'
        };
        coreMock.getInput.mockImplementation((name) => inputs[name] || '');
        execFileSyncMock.mockReturnValue('abc123 Update');
        createCompletionMock.mockResolvedValue({
          choices: [{ message: { content: '## Highlights\n- Update' } }]
        });
        await run();
        expect(coreMock.setFailed).not.toHaveBeenCalled();
        const request = createCompletionMock.mock.calls[0][0];
        expect(request.model).toBe(expected);
        expect(coreMock.setOutput).toHaveBeenCalledWith(
          'release_notes',
          '## Highlights\n- Update\n\n---\n' +
            `Generated by [Castoff](https://github.com/everydaydevopsio/castoff) using OpenAI model \`${expected}\`.`
        );
        expect(coreMock.setOutput).toHaveBeenCalledWith('model', expected);
        expect(request).not.toHaveProperty('temperature');
      } finally {
        if (previous === undefined) delete process.env.OPENAI_MODEL;
        else process.env.OPENAI_MODEL = previous;
      }
    }
  );

  it('handles missing previous tag and still sets release notes output', async () => {
    coreMock.getInput.mockImplementation((name) => {
      if (name === 'openai_api_key') return 'test-key';
      if (name === 'model') return '';
      if (name === 'tag') return 'v1.2.3';
      if (name === 'max_commits') return '';
      return '';
    });

    execFileSyncMock.mockImplementation((_cmd, args) => {
      if (args[0] === 'describe') {
        throw new Error('no previous tag');
      }
      if (args[0] === 'log') {
        return 'abc123 Fix bug\ndef456 Add feature';
      }
      throw new Error('unexpected git args');
    });

    createCompletionMock.mockResolvedValue({
      choices: [{ message: { content: '## Highlights\n\n- Fixed bug' } }]
    });

    await run();

    expect(execFileSyncMock).toHaveBeenCalledWith(
      'git',
      ['describe', '--tags', '--abbrev=0', 'HEAD^'],
      { encoding: 'utf8' }
    );
    expect(execFileSyncMock).toHaveBeenCalledWith(
      'git',
      ['log', '--pretty=format:%h %s', 'HEAD', '-n', '200'],
      { encoding: 'utf8' }
    );
    expect(coreMock.info).toHaveBeenCalledWith(
      'No previous tag found (first release).'
    );
    expect(coreMock.setOutput).toHaveBeenCalledWith(
      'release_notes',
      expect.stringMatching(
        /^## Highlights\n\n- Fixed bug\n\n---\nGenerated by \[Castoff\]/
      )
    );
    expect(coreMock.setFailed).not.toHaveBeenCalled();
  });

  it('fails fast on invalid max_commits input', async () => {
    coreMock.getInput.mockImplementation((name) => {
      if (name === 'openai_api_key') return 'test-key';
      if (name === 'model') return 'gpt-4.1-mini';
      if (name === 'tag') return 'v1.2.3';
      if (name === 'max_commits') return 'abc';
      return '';
    });

    await run();

    expect(coreMock.setFailed).toHaveBeenCalledWith(
      "Input 'max_commits' must be an integer between 1 and 1000."
    );
    expect(execFileSyncMock).not.toHaveBeenCalled();
    expect(createCompletionMock).not.toHaveBeenCalled();
  });

  it('returns fallback notes when completion content is missing', async () => {
    coreMock.getInput.mockImplementation((name) => {
      if (name === 'openai_api_key') return 'test-key';
      if (name === 'model') return 'gpt-4.1-mini';
      if (name === 'tag') return 'v9.9.9';
      if (name === 'max_commits') return '10';
      return '';
    });

    execFileSyncMock.mockImplementation((_cmd, args) => {
      if (args[0] === 'describe') return 'v9.9.8';
      if (args[0] === 'log') return 'abc123 Update docs';
      throw new Error('unexpected git args');
    });

    createCompletionMock.mockResolvedValue({
      choices: [{ message: {} }]
    });

    await run();

    expect(coreMock.setOutput).toHaveBeenCalledWith(
      'release_notes',
      '# Release v9.9.9\n\n_Auto-generated notes unavailable._\n\n---\n' +
        'Generated by [Castoff](https://github.com/everydaydevopsio/castoff) using OpenAI model `gpt-4.1-mini`.'
    );
    expect(coreMock.setFailed).not.toHaveBeenCalled();
  });

  it('fails the action when OpenAI call errors', async () => {
    coreMock.getInput.mockImplementation((name) => {
      if (name === 'openai_api_key') return 'test-key';
      if (name === 'model') return 'gpt-4.1-mini';
      if (name === 'tag') return 'v2.0.0';
      if (name === 'max_commits') return '10';
      return '';
    });

    execFileSyncMock.mockImplementation((_cmd, args) => {
      if (args[0] === 'describe') return 'v1.9.9';
      if (args[0] === 'log') return 'abc123 Add feature';
      throw new Error('unexpected git args');
    });

    createCompletionMock.mockRejectedValue(new Error('OpenAI unavailable'));

    await run();

    expect(coreMock.setFailed).toHaveBeenCalledWith('OpenAI unavailable');
  });

  it('reports non-Error exceptions as action failures', async () => {
    coreMock.getInput.mockImplementation(() => {
      throw 'unexpected input failure';
    });

    await run();

    expect(coreMock.setFailed).toHaveBeenCalledWith('unexpected input failure');
    expect(execFileSyncMock).not.toHaveBeenCalled();
    expect(createCompletionMock).not.toHaveBeenCalled();
  });
});
