import { describe, expect, it } from '@jest/globals';
import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const workflow = readFileSync(
  new URL('../.github/workflows/e2e-ai-release-notes.yml', import.meta.url),
  'utf8'
);
const verification = workflow
  .split('- name: Verify output\n')[1]
  .split('run: |\n')[1]
  .replace(/^ {10}/gm, '');

const VALID_NOTES = '## Highlights\n- Update';
const VALID_ENTRY =
  '## [0.0.0-e2e-test] - 2026-09-17\n\n### Highlights\n- Update';
const FOOTER =
  '\n\n---\nGenerated by [Castoff](https://github.com/everydaydevopsio/castoff) using OpenAI model `gpt-6-astra`.';

type Env = {
  notes?: string;
  entry?: string;
  resolvedModel?: string;
  expectedModel?: string;
};

function verify({
  notes = VALID_NOTES,
  entry = VALID_ENTRY,
  resolvedModel = 'gpt-6-astra',
  expectedModel = 'gpt-6-astra'
}: Env) {
  // Simulate a host without Linux's /proc filesystem (for example macOS).
  const portableHost =
    'cat() { case "$*" in /proc/*) return 1 ;; *) command cat "$@" ;; esac; };\n';
  const script =
    portableHost +
    verification
      .replaceAll('${{ steps.ai_notes.outputs.release_notes }}', notes)
      .replaceAll('${{ steps.ai_notes.outputs.changelog_entry }}', entry);
  return spawnSync('bash', ['-e', '-c', script], {
    env: {
      ...process.env,
      RELEASE_NOTES: notes,
      CHANGELOG_ENTRY: entry,
      RELEASE_TAG: 'v0.0.0-e2e-test',
      RESOLVED_MODEL: resolvedModel,
      EXPECTED_MODEL: expectedModel
    },
    encoding: 'utf8',
    timeout: 10000
  });
}

describe('E2E release notes verification', () => {
  it.each([
    [
      '## Highlights\n- Keep `printf BACKTICK_EXECUTED` and $(printf SUBSTITUTION_EXECUTED) literal.\n- Quotes: "text"\n::error::literal annotation\n::add-mask::literal mask',
      0
    ],
    ['', 1],
    ['Unexpected output', 1],
    ['# Release v1.0.0\n\n_Auto-generated notes unavailable._', 1]
  ])(
    'treats notes as data and validates their structure: %s',
    (notes, status) => {
      const result = verify({ notes });

      expect(result.error).toBeUndefined();
      expect(result.status).toBe(status);
      const marker = result.stdout.match(/::stop-commands::([a-f0-9-]+)\n/);
      expect(marker).not.toBeNull();
      expect(result.stdout).toContain(
        `::stop-commands::${marker?.[1]}\n${notes}\n${VALID_ENTRY}\n::${marker?.[1]}::\n`
      );
      expect(result.stderr).toBe('');
    }
  );
});

describe('E2E changelog entry verification', () => {
  it('accepts an entry headed by the release version and an ISO date', () => {
    const result = verify({});

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('✓ E2E test passed');
  });

  it.each([
    ['empty entry', ''],
    ['wrong version', '## [9.9.9] - 2026-09-17\n\n### Highlights\n- Update'],
    [
      'malformed date',
      '## [0.0.0-e2e-test] - 17-09-2026\n\n### Highlights\n- Update'
    ],
    ['missing version heading', '### Highlights\n- Update']
  ])('rejects a changelog entry with a %s', (_case, entry) => {
    const result = verify({ entry });

    expect(result.status).toBe(1);
    expect(result.stdout).toContain('changelog_entry');
  });

  it('rejects a changelog entry that carries the attribution footer', () => {
    const result = verify({ entry: VALID_ENTRY + FOOTER });

    expect(result.status).toBe(1);
    expect(result.stdout).toContain('attribution footer');
  });
});

it('rejects a live model that differs from the expected matrix model', () => {
  const result = verify({ expectedModel: 'gpt-5.6-sol' });

  expect(result.status).toBe(1);
  expect(result.stdout).toContain(
    'ERROR: selected model does not match expected model'
  );
});
